<template>
  <div class="promotion-admin" v-loading="loading">
    <header class="pane-head"><div><h2>推广服务</h2><p>推广订单必须核对实收金额、收款流水和四位付款秘钥后人工启用；这里只处理推广服务费。</p></div><el-button @click="load">刷新</el-button></header>
    <el-alert type="warning" :closable="false" show-icon title="所有推广展示必须保留“置顶、加急、推广”标签；不得伪装成普通评价或自然推荐。" />
    <section class="stats"><article><b>{{ overview.counts.pendingOrders }}</b><span>待付款/核验</span></article><article><b>{{ overview.counts.waitlistedOrders }}</b><span>候补订单</span></article><article><b>¥{{ overview.revenue }}</b><span>已确认推广额</span></article><article><b>¥{{ overview.netContribution }}</b><span>扣除退款、补偿与人工成本</span></article><article><b>{{ overview.complaintCount }}</b><span>投诉留痕</span></article></section>
    <el-tabs v-model="tab">
      <el-tab-pane label="推广订单" name="orders">
        <div class="toolbar"><el-select v-model="orderFilter.status" clearable placeholder="全部状态" @change="loadOrders"><el-option label="候补中" value="waitlisted" /><el-option label="待付款/核验" value="pending" /><el-option label="推广中" value="confirmed" /><el-option label="已到期" value="expired" /><el-option label="未通过" value="rejected" /><el-option label="已取消" value="cancelled" /></el-select><el-select v-model="orderFilter.type" clearable placeholder="全部类型" @change="loadOrders"><el-option v-for="type in typeOptions" :key="type.value" :label="type.label" :value="type.value" /></el-select><el-input v-model="orderFilter.q" clearable placeholder="订单号、方案或用户" @keyup.enter="loadOrders" /><el-button @click="loadOrders">查询</el-button></div>
        <el-table :data="orders" stripe>
          <el-table-column label="订单 / 用户" min-width="190"><template #default="{row}"><b>{{ row.outTradeNo }}</b><small>{{ row.user?.nickname || `用户 #${row.userId}` }} · {{ formatTime(row.createdAt) }}</small></template></el-table-column>
          <el-table-column label="方案与对象" min-width="220"><template #default="{row}"><PromotionLabel :label="row.badgeLabel" :kind="kindFor(row.type)" /> <b>{{ row.planName }}</b><small>{{ targetTitle(row) }}</small></template></el-table-column>
          <el-table-column label="费用" width="90"><template #default="{row}">¥{{ row.amount }}</template></el-table-column>
          <el-table-column label="付款核验 / 售后" min-width="210"><template #default="{row}"><template v-if="row.verifiedAmount"><b>{{ verificationMethodLabel(row.verificationMethod) }} · ¥{{ row.verifiedAmount }}</b><small>{{ row.verificationReference || row.verificationReferenceMasked }} · {{ row.reviewedBy?.nickname || '管理员' }}</small></template><template v-else-if="row.paymentSubmittedAt"><b>用户已确认付款</b><small>{{ formatTime(row.paymentSubmittedAt) }} · 秘钥 {{ row.paymentCode }}</small></template><small v-else-if="row.status==='pending'">等待用户付款并确认秘钥 {{ row.paymentCode }}</small><small v-else-if="row.status==='waitlisted'">位置已满，尚未进入付款</small><small v-else>尚无核验记录</small><small v-if="row.adjustments?.length">{{ row.adjustments.length }} 条售后留痕 · 最近：{{ adjustmentTypeLabel(row.adjustments[row.adjustments.length - 1]?.type) }}</small></template></el-table-column>
          <el-table-column label="数据" width="145"><template #default="{row}"><span>曝光 {{ row.impressionCount }} / 点击 {{ row.clickCount }}</span><small>CTR {{ row.ctr }}%</small></template></el-table-column>
          <el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="orderStatusType(row.status)">{{ orderStatusLabel(row.status) }}</el-tag></template></el-table-column>
          <el-table-column label="操作" width="250"><template #default="{row}"><template v-if="['pending','waitlisted'].includes(row.status)"><el-button v-if="row.status==='pending'" link type="success" :disabled="!row.paymentSubmittedAt" @click="reviewOrder(row,'confirm')">{{ row.paymentSubmittedAt ? '核验到账' : '等待付款' }}</el-button><el-button link type="danger" @click="reviewOrder(row,'reject')">{{ row.paymentSubmittedAt ? '驳回并联系退款' : '驳回' }}</el-button></template><el-button v-if="['confirmed','expired'].includes(row.status)" link type="warning" @click="openAdjustment(row)">售后留痕</el-button><router-link v-if="targetLink(row)" :to="targetLink(row)"><el-button link>查看对象</el-button></router-link></template></el-table-column>
        </el-table><el-empty v-if="!orders.length" description="暂无推广订单" />
      </el-tab-pane>
      <el-tab-pane label="价格配置" name="plans">
        <div class="table-note"><h3>推广方案与价格</h3><p>价格和时长保存在数据库中；新订单会保存当时的方案快照，后续调价不影响历史订单。</p></div>
        <el-table :data="overview.plans" stripe><el-table-column prop="name" label="方案" min-width="180" /><el-table-column prop="badgeLabel" label="标识" width="90" /><el-table-column label="价格 / 人工成本" width="150"><template #default="{row}"><b>¥{{ row.price }}</b><small>成本 ¥{{ row.manualCost }}</small></template></el-table-column><el-table-column label="时长 / 库存" width="130"><template #default="{row}"><b>{{ row.durationDays }} 天</b><small>{{ row.maxActive ? `同时最多 ${row.maxActive} 个` : '不设上限' }}</small></template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{ row.enabled?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column prop="description" label="说明" min-width="220" show-overflow-tooltip /><el-table-column label="操作" width="80"><template #default="{row}"><el-button link type="primary" @click="editPlan(row)">编辑</el-button></template></el-table-column></el-table>
      </el-tab-pane>
    </el-tabs>
    <el-dialog v-model="confirmOpen" title="人工确认平台盈利订单" width="520px" destroy-on-close><el-alert type="warning" :closable="false" show-icon title="仅在收款渠道中同时核对实收金额、流水号和付款备注四位秘钥后启用。学生商品款不得在此确认。" /><el-form label-position="top" class="confirm-form"><div class="two-cols"><el-form-item label="核验渠道" required><el-select v-model="confirmForm.verificationMethod"><el-option label="支付宝" value="alipay" /><el-option label="微信支付" value="wechat" /><el-option label="银行转账" value="bank" /><el-option label="现金" value="cash" /><el-option label="其他" value="other" /></el-select></el-form-item><el-form-item label="实收金额（元）" required><el-input-number v-model="confirmForm.verifiedAmount" :min="0" :max="999999" :precision="2" /></el-form-item></div><div class="two-cols"><el-form-item label="核验凭证号 / 流水号" required><el-input v-model="confirmForm.verificationReference" maxlength="120" placeholder="填写必要的外部流水编号" /></el-form-item><el-form-item label="付款备注四位秘钥" required><el-input v-model="confirmForm.paymentCode" maxlength="4" inputmode="numeric" placeholder="以收款记录备注为准" /></el-form-item></div><el-form-item label="人工确认说明" required><el-input v-model="confirmForm.note" type="textarea" :rows="3" maxlength="500" show-word-limit placeholder="例如：已核对实收金额、收款流水、付款备注秘钥和推广对象" /></el-form-item><div v-if="reviewingOrder" class="order-snapshot"><span>订单快照</span><b>{{ reviewingOrder.planName }} · ¥{{ reviewingOrder.amount }} · {{ targetTitle(reviewingOrder) }}</b><small>系统订单秘钥：{{ reviewingOrder.paymentCode }} · 用户确认时间：{{ reviewingOrder.paymentSubmittedAt ? formatTime(reviewingOrder.paymentSubmittedAt) : '未确认' }}</small></div></el-form><template #footer><el-button @click="confirmOpen=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitConfirmation">确认到账并启用推广</el-button></template></el-dialog>
    <el-dialog v-model="adjustmentOpen" title="推广服务售后留痕" width="540px" destroy-on-close><el-alert type="info" :closable="false" show-icon title="退款、补偿和票据仅登记线下处理结果，不会自动退款或自动开票；所有动作都会写入管理员审计记录。" /><el-form label-position="top" class="confirm-form"><el-form-item label="记录类型" required><el-select v-model="adjustmentForm.type" style="width:100%"><el-option v-for="option in adjustmentOptions" :key="option.value" :label="option.label" :value="option.value" /></el-select></el-form-item><div class="two-cols"><el-form-item v-if="adjustmentForm.type==='service_extension'" label="延长天数" required><el-input-number v-model="adjustmentForm.extensionDays" :min="1" :max="365" /></el-form-item><el-form-item v-else-if="['refund_record','compensation_record','invoice_record'].includes(adjustmentForm.type)" label="记录金额（元）"><el-input-number v-model="adjustmentForm.amount" :min="0" :max="adjustingOrder ? Number(adjustingOrder.amount) : 0" :precision="2" /></el-form-item><el-form-item label="外部凭证号"><el-input v-model="adjustmentForm.reference" maxlength="120" :placeholder="['refund_record','invoice_record'].includes(adjustmentForm.type) ? '必填，仅保存必要编号' : '选填'" /></el-form-item></div><el-form-item label="处理说明" required><el-input v-model="adjustmentForm.note" type="textarea" :rows="3" maxlength="500" show-word-limit /></el-form-item><div v-if="adjustingOrder" class="order-snapshot"><span>订单快照</span><b>{{ adjustingOrder.planName }} · ¥{{ adjustingOrder.amount }} · {{ targetTitle(adjustingOrder) }}</b></div></el-form><template #footer><el-button @click="adjustmentOpen=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitAdjustment">写入人工记录</el-button></template></el-dialog>
    <el-dialog v-model="planOpen" title="编辑推广方案" width="540px"><el-form label-position="top"><el-form-item label="方案名称"><el-input v-model="planForm.name" maxlength="80" /></el-form-item><div class="two-cols"><el-form-item label="价格（元）"><el-input-number v-model="planForm.price" :min="0" :max="999999" :precision="2" /></el-form-item><el-form-item label="单笔人工成本（元）"><el-input-number v-model="planForm.manualCost" :min="0" :max="999999" :precision="2" /></el-form-item><el-form-item label="时长（天）"><el-input-number v-model="planForm.durationDays" :min="1" :max="365" /></el-form-item><el-form-item label="同时生效库存"><el-input-number v-model="planForm.maxActive" :min="0" :max="10000" :disabled="fixedCapacityPlan" /><small>{{ fixedCapacityPlan ? '首页商品和热议求购容量固定为 8' : '0 表示不设上限；同对象续期不额外占位' }}</small></el-form-item></div><el-form-item label="说明"><el-input v-model="planForm.description" type="textarea" :rows="3" maxlength="500" /></el-form-item><el-switch v-model="planForm.enabled" active-text="启用" inactive-text="停用" /></el-form><template #footer><el-button @click="planOpen=false">取消</el-button><el-button type="primary" :loading="saving" @click="savePlan">保存</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { marketApi, type PromotionOrder, type PromotionPlan } from "@/api/market";
import PromotionLabel from "@/components/market/PromotionLabel.vue";
const tab=ref("orders"),loading=ref(false),saving=ref(false),orders=ref<PromotionOrder[]>([]),planOpen=ref(false),editingPlanId=ref(0),confirmOpen=ref(false),reviewingOrder=ref<PromotionOrder|null>(null),adjustmentOpen=ref(false),adjustingOrder=ref<PromotionOrder|null>(null);
const overview=reactive({plans:[] as PromotionPlan[],counts:{pendingOrders:0,waitlistedOrders:0,confirmedOrders:0},revenue:"0.00",revenueCents:0,refundCents:0,compensationCents:0,manualCostCents:0,netContributionCents:0,netContribution:"0.00",complaintCount:0,impressions:0,clicks:0});
const orderFilter=reactive({q:"",status:"",type:""});
const planForm=reactive({name:"",description:"",price:0,manualCost:0,durationDays:7,maxActive:0,enabled:true});
const confirmForm=reactive({verificationMethod:"alipay" as "alipay"|"wechat"|"bank"|"cash"|"other",verifiedAmount:0,verificationReference:"",paymentCode:"",note:""});
const fixedCapacityPlan=computed(()=>["home_featured","wanted_urgent"].includes(overview.plans.find((plan)=>plan.id===editingPlanId.value)?.type||""));
const adjustmentForm=reactive({type:"service_extension" as "service_extension"|"refund_record"|"compensation_record"|"invoice_record"|"complaint_record",amount:0,extensionDays:1,reference:"",note:""});
const adjustmentOptions=[{value:"service_extension",label:"服务延期"},{value:"refund_record",label:"退款留痕（不自动退款）"},{value:"compensation_record",label:"补偿留痕"},{value:"invoice_record",label:"票据留痕（不自动开票）"},{value:"complaint_record",label:"投诉留痕"}] as const;
const typeOptions=[{value:"listing_pin",label:"商品置顶"},{value:"wanted_urgent",label:"求购加急"},{value:"home_featured",label:"首页推广"}];
onMounted(load);
async function load(){loading.value=true;try{const [nextOverview,nextOrders]=await Promise.all([marketApi.adminPromotionOverview({suppressErrorMessage:true}),marketApi.adminPromotionOrders({page:1,size:100,...orderFilter},{suppressErrorMessage:true})]);Object.assign(overview,nextOverview);orders.value=nextOrders.list;}finally{loading.value=false}}
async function loadOrders(){const result=await marketApi.adminPromotionOrders({page:1,size:100,...orderFilter});orders.value=result.list}
async function reviewOrder(order:PromotionOrder,action:"confirm"|"reject"){if(action==="confirm"){if(!order.paymentSubmittedAt)return void ElMessage.warning("用户尚未在订单页确认付款秘钥");reviewingOrder.value=order;Object.assign(confirmForm,{verificationMethod:"alipay",verifiedAmount:Number(order.amount),verificationReference:"",paymentCode:"",note:""});confirmOpen.value=true;return}const paid=Boolean(order.paymentSubmittedAt);const result=await ElMessageBox.prompt(paid?"该订单已确认付款。请填写驳回原因和联系用户退款的安排；系统不会自动退款。":"请填写驳回原因",paid?"驳回并联系退款":"驳回推广申请",{inputPattern:/\S{2,}/,inputErrorMessage:"请至少填写 2 个字符",confirmButtonText:paid?"确认驳回并联系退款":"确认驳回"});await marketApi.adminUpdatePromotionOrder(order.id,{action,note:result.value});ElMessage.success(paid?"订单已驳回，请按说明联系用户完成退款":"推广申请已驳回");await load()}
async function submitConfirmation(){const order=reviewingOrder.value;if(!order)return;if(Math.round(confirmForm.verifiedAmount*100)!==order.amountCents)return void ElMessage.warning("实收金额必须与订单快照金额一致");if(confirmForm.verificationReference.trim().length<2)return void ElMessage.warning("请填写核验凭证号或流水号");if(!/^\d{4}$/.test(confirmForm.paymentCode))return void ElMessage.warning("请填写收款记录中的四位付款秘钥");if(confirmForm.paymentCode!==order.paymentCode)return void ElMessage.warning("付款备注秘钥与系统订单秘钥不一致");if(confirmForm.note.trim().length<2)return void ElMessage.warning("请填写人工确认说明");saving.value=true;try{await marketApi.adminUpdatePromotionOrder(order.id,{action:"confirm",...confirmForm});confirmOpen.value=false;ElMessage.success("盈利订单已人工确认，推广开始生效");await load()}finally{saving.value=false}}
function editPlan(plan:PromotionPlan){editingPlanId.value=plan.id;Object.assign(planForm,{name:plan.name,description:plan.description,price:Number(plan.price),manualCost:Number(plan.manualCost),durationDays:plan.durationDays,maxActive:["home_featured","wanted_urgent"].includes(plan.type)?8:plan.maxActive,enabled:plan.enabled});planOpen.value=true}
async function savePlan(){saving.value=true;try{await marketApi.adminUpdatePromotionPlan(editingPlanId.value,planForm);planOpen.value=false;ElMessage.success("推广价格配置已保存");await load()}finally{saving.value=false}}
function openAdjustment(order:PromotionOrder){adjustingOrder.value=order;Object.assign(adjustmentForm,{type:"service_extension",amount:0,extensionDays:1,reference:"",note:""});adjustmentOpen.value=true}
async function submitAdjustment(){const order=adjustingOrder.value;if(!order)return;if(adjustmentForm.note.trim().length<2)return void ElMessage.warning("请填写至少 2 个字符的处理说明");if(["refund_record","invoice_record"].includes(adjustmentForm.type)&&adjustmentForm.reference.trim().length<2)return void ElMessage.warning("退款或票据记录必须填写外部凭证号");saving.value=true;try{await marketApi.adminCreatePromotionAdjustment(order.id,adjustmentForm);adjustmentOpen.value=false;ElMessage.success("人工售后记录已写入审计链");await load()}finally{saving.value=false}}
function kindFor(type:PromotionPlan["type"]){return type==="listing_pin"?"pin":type==="wanted_urgent"?"urgent":"home"}function targetTitle(row:PromotionOrder){return row.marketItem?.title||row.wantedPost?.title||"推广对象已移除"}function targetLink(row:PromotionOrder){return row.marketItem?`/market/item/${row.marketItem.id}`:row.wantedPost?`/market/wanted/${row.wantedPost.id}`:""}function orderStatusLabel(status:PromotionOrder["status"]){return({waitlisted:"候补中",pending:"待付款/核验",confirmed:"推广中",rejected:"未通过",cancelled:"已取消",expired:"已到期"}as const)[status]}function orderStatusType(status:PromotionOrder["status"]){return status==="confirmed"?"success":["pending","waitlisted"].includes(status)?"warning":status==="rejected"?"danger":"info"}function formatTime(value:string){return new Date(value).toLocaleString("zh-CN")}function adjustmentTypeLabel(value?:string){return adjustmentOptions.find((option)=>option.value===value)?.label||"人工记录"}
function verificationMethodLabel(value:string){return({alipay:"支付宝",wechat:"微信支付",bank:"银行转账",cash:"现金",other:"其他",manual_admin:"兼容人工确认"}as Record<string,string>)[value]||"人工核验"}
</script>

<style scoped>
.promotion-admin{padding:4px}.pane-head{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:14px}.pane-head h2{margin:0 0 5px}.pane-head p,.table-note p{margin:0;color:var(--cpu-text-secondary);font-size:11px}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin:14px 0}.stats article{display:flex;align-items:center;flex-direction:column;padding:13px;border:1px solid var(--cpu-border-soft);border-radius:10px;text-align:center}.stats b{font-size:21px}.stats span{color:var(--cpu-text-secondary);font-size:9px}.toolbar{display:grid;grid-template-columns:150px 150px minmax(0,1fr) auto;gap:8px;margin-bottom:12px}.el-table b,.el-table small{display:block}.el-table small{margin-top:3px;color:var(--cpu-text-secondary);font-size:9px}.overdue{color:var(--cpu-danger)}.table-note{margin-bottom:12px}.table-note h3{margin-bottom:4px}.two-cols{display:grid;grid-template-columns:1fr 1fr;gap:14px}.two-cols small{display:block;margin-top:5px;color:var(--cpu-text-secondary);font-size:10px}.confirm-form{margin-top:15px}.order-snapshot{display:flex;flex-direction:column;gap:5px;padding:11px;border-radius:9px;background:var(--cpu-surface-soft)}.order-snapshot span,.order-snapshot small{color:var(--cpu-text-secondary);font-size:9px}.order-snapshot b{font-size:11px}@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}.toolbar{grid-template-columns:1fr 1fr}.toolbar .el-input{grid-column:1/-1}}@media(max-width:520px){.stats{grid-template-columns:1fr 1fr}.toolbar,.two-cols{grid-template-columns:1fr}.toolbar .el-input{grid-column:auto}}
</style>
