name: cpu_flutter_client
description: 靠浦移动客户端外壳。
publish_to: "none"
version: 3.0.1+22

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
