<template>
  <div class="library-page">
    <header><div><span>MY LEARNING LIBRARY</span><h1>{{ isEnglish ? "My Learning Library" : "我的资料库" }}</h1><p>{{ isEnglish ? "Delivered paid materials and previously claimed content are kept here. Access logs support file security and issue resolution." : "已完成交付的付费资料和历史已领取内容保存在这里，访问记录用于文件安全和售后定位。" }}</p></div><div><el-button @click="router.push({name:'market-learning-orders'})">{{ isEnglish ? "Material orders" : "资料订单" }}</el-button><el-button type="primary" @click="router.push({name:'market-learning-materials'})">{{ isEnglish ? "Discover more" : "继续发现内容" }}</el-button></div></header>
    <div v-if="loading" class="library-grid"><article v-for="i in 4" :key="i" class="cpu-card"><el-skeleton animated :rows="5" /></article></div>
    <div v-else-if="entries.length" class="library-grid"><article v-for="entry in entries" :key="entry.id" class="library-card cpu-card"><div class="cover" @click="openItem(entry.version.profile.item.id)"><img v-if="entry.version.profile.item.cover" :src="entry.version.profile.item.cover" :alt="entry.version.profile.item.title" /><img v-else src="/brand/kaopu-cloud.svg" alt="" /></div><div class="copy"><div class="tags"><span>{{ entry.version.profile.courseCode }}</span><span>{{ semesterLabel(entry.version.profile.applicableSemester) }}</span></div><h2>{{ entry.version.profile.item.title }}</h2><p>{{ isEnglish ? "Version" : "版本" }} {{ entry.version.label||`v${entry.version.versionNumber}` }} · {{ isEnglish ? "Unlocked" : "解锁于" }} {{ formatDate(entry.grantedAt) }}</p><div class="files"><a v-for="file in entry.version.files" :key="file.id" :href="learningMaterialsApi.downloadUrl(file.id)"><b>{{file.originalName}}</b><span>{{file.format}} · {{formatBytes(file.fileSize)}}</span><em>{{ isEnglish ? "Download" : "下载" }}</em></a></div><footer><span>{{ isEnglish ? "Downloaded" : "已下载" }} {{entry.downloadCount}} {{ isEnglish ? "times" : "次" }}</span><el-button size="small" type="primary" plain @click="openSupport(entry.order.id)">{{ isEnglish ? "Report issue" : "问题反馈" }}</el-button></footer></div></article></div>
    <el-empty v-else :description="isEnglish ? 'No unlocked learning materials yet' : '还没有已解锁的学习资料'"><el-button type="primary" @click="router.push({name:'market-learning-materials'})">{{ isEnglish ? "Browse paid materials" : "浏览付费资料" }}</el-button></el-empty>
  </div>
</template>
<script setup lang="ts">
import { onMounted,reactive,ref } from "vue";import { useRouter } from "vue-router";import dayjs from "dayjs";import { learningMaterialsApi,type LearningMaterialLibraryEntry,type LearningMaterialMeta } from "@/api/learningMaterials";import { useLocale } from "@/i18n";
const router=useRouter(),{isEnglish}=useLocale(),entries=ref<LearningMaterialLibraryEntry[]>([]),loading=ref(false);const meta=reactive<LearningMaterialMeta>({category:{id:0,slug:"digital_goods",name:"电子资料",icon:"📁",description:"",fulfillmentType:"digital",imageRequired:false,enabled:true,sort:30,itemCount:0},semesters:[],formats:[],languages:[],originalityOptions:[],supportCategories:[],types:[],legacyIncompleteCount:0});onMounted(async()=>{loading.value=true;try{const [list,nextMeta]=await Promise.all([learningMaterialsApi.library({suppressErrorMessage:true}),learningMaterialsApi.meta({suppressErrorMessage:true})]);entries.value=list;Object.assign(meta,nextMeta)}finally{loading.value=false}});function semesterLabel(value:string){const label=meta.semesters.find(row=>row.value===value)?.label||value;if(!isEnglish.value)return label;return ({spring:"Spring",summer:"Summer",autumn:"Autumn",fall:"Autumn",winter:"Winter",full_year:"Full year"} as Record<string,string>)[value.toLowerCase()]||label}function formatDate(value:string){return dayjs(value).format("YYYY-MM-DD")}function formatBytes(value:number){return value<1024*1024?`${Math.max(1,Math.round(value/1024))} KB`:`${(value/1024/1024).toFixed(1)} MB`}function openItem(id:number){router.push({name:"market-learning-material-item",params:{id}})}function openSupport(orderId:number){router.push({name:"market-learning-material-support",query:{order:String(orderId)}})}
</script>
<style scoped>
.library-page{max-width:1180px;margin:0 auto;display:flex;flex-direction:column;gap:20px}.library-page>header{display:flex;align-items:flex-end;justify-content:space-between;gap:20px}.library-page>header span{color:#a21caf;font-size:9px;font-weight:800;letter-spacing:.17em}.library-page h1{margin:5px 0;font-size:30px}.library-page header p{margin:0;color:var(--cpu-text-secondary);font-size:12px}.library-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.library-card{display:grid;grid-template-columns:180px 1fr;gap:17px;padding:16px}.cover{display:grid;place-items:center;height:210px;overflow:hidden;border-radius:12px;background:#fdf2f8;cursor:pointer}.cover img{width:100%;height:100%;object-fit:contain}.copy{min-width:0}.tags{display:flex;gap:5px}.tags span{padding:3px 6px;border-radius:5px;color:#86198f;background:#fae8ff;font-size:8px}.copy h2{margin:9px 0 5px;overflow:hidden;font-size:16px;white-space:nowrap;text-overflow:ellipsis}.copy>p{margin:0 0 12px;color:var(--cpu-text-secondary);font-size:9px}.files{display:flex;flex-direction:column;gap:6px}.files a{display:grid;grid-template-columns:1fr auto;gap:2px 8px;padding:8px;border:1px solid var(--cpu-border-soft);border-radius:8px;color:inherit;text-decoration:none}.files b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:9px}.files span{color:var(--cpu-text-secondary);font-size:8px}.files em{grid-column:2;grid-row:1/3;align-self:center;color:#a21caf;font-size:9px;font-style:normal}.copy footer{display:flex;align-items:center;justify-content:space-between;margin-top:12px}.copy footer>span{color:var(--cpu-text-secondary);font-size:8px}@media(max-width:900px){.library-grid{grid-template-columns:1fr}}@media(max-width:560px){.library-page>header{align-items:flex-start;flex-direction:column}.library-card{grid-template-columns:1fr}.cover{height:190px}}
</style>
