<template>
  <div class="merchant-apply">
    <header class="page-head"><div><span>MERCHANT APPLICATION</span><h1>合作商户资料</h1><p>提交服务与经营信息供管理员审核。审核通过不等于自动上线，主页还需单独确认推广订单。</p></div><el-button @click="$router.push('/market/promotions')">返回推广中心</el-button></header>
    <el-alert v-if="profile" :type="statusType(profile.status)" show-icon :closable="false" :title="statusCopy" />
    <el-form class="profile-form cpu-card" label-position="top" v-loading="loading">
      <section><h2>主页信息</h2><div class="two-cols"><el-form-item label="商户或服务名称" required><el-input v-model="form.name" maxlength="80" /></el-form-item><el-form-item label="主页地址" required><el-input v-model="form.slug" maxlength="40"><template #prepend>/market/merchant/</template></el-input></el-form-item></div><div class="two-cols"><el-form-item label="服务分类" required><el-select v-model="form.category" filterable allow-create default-first-option style="width:100%"><el-option v-for="category in categories" :key="category" :label="category" :value="category" /></el-select></el-form-item><el-form-item label="服务范围" required><el-input v-model="form.serviceArea" maxlength="200" placeholder="例如：南北校区，可上门" /></el-form-item></div><el-form-item label="服务介绍" required><el-input v-model="form.description" type="textarea" :rows="7" maxlength="5000" show-word-limit placeholder="说明服务项目、流程、资质或经营信息，不要伪造评价" /></el-form-item></section>
      <section><h2>价格与优惠</h2><div class="two-cols"><el-form-item label="价格范围" required><el-input v-model="form.priceRange" maxlength="200" placeholder="例如：打印 0.2 元/页起，以现场确认项目为准" /></el-form-item><el-form-item label="学生优惠"><el-input v-model="form.studentDiscount" maxlength="300" placeholder="没有可留空" /></el-form-item></div></section>
      <section><h2>展示图片</h2><p class="section-note">最多 9 张，建议使用真实门店、设备或服务场景图片。</p><div class="image-grid"><div v-for="(image,index) in form.images" :key="image" class="image-cell"><img :src="image" alt="商户图片" /><button type="button" @click="form.images.splice(index,1)">×</button></div><label v-if="form.images.length<9" class="upload-cell" :class="{disabled:uploading}"><input type="file" accept="image/*" multiple :disabled="uploading" @change="uploadImages" /><span>{{ uploading ? `${uploadProgress}%` : '+' }}</span><b>{{ uploading ? '上传中' : '添加图片' }}</b></label></div></section>
      <section><h2>业务联系方式</h2><p class="section-note">联系方式加密保存；公开页只显示脱敏值，已登录并验证校园身份的同学主动咨询后才能查看。{{ profile?.contactValueMasked ? `当前：${profile.contactValueMasked}` : '' }}</p><div class="two-cols"><el-form-item label="联系类型" required><el-select v-model="form.contactMethod" style="width:100%"><el-option label="微信" value="wechat" /><el-option label="QQ" value="qq" /><el-option label="电话" value="phone" /><el-option label="邮箱" value="email" /><el-option label="网站" value="website" /><el-option label="其他" value="other" /></el-select></el-form-item><el-form-item label="联系方式" required><el-input v-model="form.contactValue" maxlength="300" :placeholder="profile ? '为保护隐私，编辑时请重新填写' : '填写公开业务联系方式'" /></el-form-item></div></section>
      <el-alert type="warning" :closable="false" show-icon title="禁止发布代写代考、违规资料、贷款套现、账号交易等内容；所有商业展示都会明确标注“合作商户”或“推广”。" />
      <div class="form-actions"><el-button @click="$router.push('/market/promotions')">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">提交审核</el-button></div>
    </el-form>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { marketApi, type MerchantProfile } from "@/api/market";
import { uploadApi } from "@/api/topic";

const categories = ["打印装订", "电脑维修", "手机维修", "搬运寄存", "摄影与证件照", "校园周边餐饮", "其他合规服务"];
const profile = ref<MerchantProfile | null>(null), loading = ref(false), submitting = ref(false), uploading = ref(false), uploadProgress = ref(0);
const form = reactive({ slug: "", name: "", category: "", description: "", priceRange: "", serviceArea: "", studentDiscount: "", contactMethod: "wechat", contactValue: "", images: [] as string[] });
const statusCopy = computed(() => profile.value?.status === "approved" ? "商户资料已审核通过，可前往推广中心申请主页启用方案。" : profile.value?.status === "reviewing" ? "资料正在人工审核，修改后会重新进入审核。" : profile.value?.status === "suspended" ? `主页已暂停：${profile.value.reviewNote || '请联系管理员核查'}` : `资料未通过：${profile.value?.reviewNote || '请修改后重新提交'}`);
onMounted(load);
async function load() { loading.value = true; try { profile.value = await marketApi.myMerchantProfile({ suppressErrorMessage: true }); if (profile.value) Object.assign(form, { slug: profile.value.slug, name: profile.value.name, category: profile.value.category, description: profile.value.description, priceRange: profile.value.priceRange, serviceArea: profile.value.serviceArea, studentDiscount: profile.value.studentDiscount, contactMethod: profile.value.contactMethod, contactValue: "", images: [...profile.value.images] }); } finally { loading.value = false; } }
async function uploadImages(event: Event) { const input = event.target as HTMLInputElement; const files = Array.from(input.files || []).slice(0, 9-form.images.length); if (!files.length) return; uploading.value = true; try { for (let index=0; index<files.length; index++) { const file=files[index]; const result=await uploadApi.media(file,file.name,{onProgress:(state)=>{uploadProgress.value=Math.round(((index+state.percent/100)/files.length)*100)}}); form.images.push(result.url); } } finally { uploading.value=false; uploadProgress.value=0; input.value=""; } }
async function submit() { if (!form.name.trim() || !form.slug.trim() || !form.category || form.description.trim().length<20 || !form.priceRange.trim() || !form.serviceArea.trim() || !form.contactValue.trim()) return ElMessage.warning("请完整填写商户资料和本次联系方式"); submitting.value=true; try { profile.value=await marketApi.saveMerchantProfile(form); form.contactValue=""; ElMessage.success("商户资料已提交人工审核"); } finally { submitting.value=false; } }
function statusType(status: MerchantProfile["status"]) { return status === "approved" ? "success" : status === "reviewing" ? "warning" : "error"; }
</script>

<style scoped>
.merchant-apply{max-width:1020px;margin:0 auto;display:flex;flex-direction:column;gap:18px}.page-head{display:flex;align-items:flex-end;justify-content:space-between;gap:20px}.page-head span{color:var(--cpu-primary);font-size:9px;font-weight:800;letter-spacing:.16em}.page-head h1{margin:6px 0}.page-head p,.section-note{margin:0;color:var(--cpu-text-secondary);font-size:11px}.profile-form{padding:25px}.profile-form section+section{margin-top:27px;padding-top:22px;border-top:1px solid var(--cpu-border-soft)}.profile-form h2{margin:0 0 15px;font-size:17px}.section-note{margin:-8px 0 13px}.two-cols{display:grid;grid-template-columns:1fr 1fr;gap:17px}.image-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.image-cell,.upload-cell{position:relative;aspect-ratio:1;overflow:hidden;border-radius:11px;background:var(--cpu-surface-soft)}.image-cell img{width:100%;height:100%;object-fit:cover}.image-cell button{position:absolute;right:5px;top:5px;width:24px;height:24px;border:0;border-radius:50%;color:#fff;background:rgba(15,23,42,.7)}.upload-cell{display:flex;align-items:center;justify-content:center;flex-direction:column;border:1px dashed var(--cpu-border);cursor:pointer}.upload-cell input{display:none}.upload-cell span{font-size:25px}.upload-cell b{font-size:10px}.form-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}@media(max-width:650px){.page-head{align-items:flex-start;flex-direction:column}.two-cols{grid-template-columns:1fr}.profile-form{padding:16px}.image-grid{grid-template-columns:repeat(3,1fr)}.form-actions .el-button{flex:1}}
</style>
